language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - sudo apt-get update -qq
    - dpkg -l | grep mesa
    - apt-cache search mesa
    - sudo apt-get install --force-yes -qq libegl1-mesa-drivers libegl1-mesa-drivers-dbg mesa-utils 
    - dpkg -l | grep mesa
    - git clone https://github.com/benlau/qtci/
    - source qtci/path.env
    - qt-5.5.1
    - cat /etc/init.d/xvfb 
    - sh -e /etc/init.d/xvfb start

script:
    - xvfb-run -a glxinfo
    - source qt-5.5.1.env
    - cd tests/quickandroidcpptests
    - qmake
    - make
    - ls
    - ./quickandroidcpptests
    - cd ../quickandroidtests
    - qmake
    - make
    - ls
    - ./quickandroidtests

